### PR TITLE
sched/ghost: allow use under CONFIG_PREEMPTION=y build

### PR DESCRIPTION
**Pull request by lkpdn**
Hi, this work looks quite fascinating to me. I'd like to use this under CONFIG_PREEMPTION=y so let me post a PR. Thanks.

### CODE REVIEW

**Comment by neelnatu** [comment]
Thanks for the patch!

There is a possibility that our internal workflow prevents syncing our repository with changes from github. In this case we'll apply the patch internally first and it will show up via our regular open source workflow in github.

The ghost.c changes look good to me but I am considering moving ghost_commit_greedy_txn() from should_resched() to the top of preempt_schedule_common().

**Comment by lkpdn** [comment]
Thank you for the comment!

> The ghost.c changes look good to me but I am considering moving ghost_commit_greedy_txn() from should_resched() to the top of preempt_schedule_common().

Sounds reasonable.
(Edited) If you don't have much time to spare, I can cook the patch. ;)

**Comment by neelnatu** [comment]
Doh, I don't know what I was thinking when I suggested moving ghost_commit_greedy_txn() into preempt_schedule_common(). The idea of having it as the first thing in should_resched() was so that we could detect that a ghost task wants preempt whatever is currently running on the cpu. Moving this out of should_resched() defeats that purpose entirely.

So, your patch is fine. I am still figuring out whether we can commit this directly or it needs to come via our internal repository.

Thanks again.

**Comment by lkpdn** [comment]
I guess, in that case, my original patch should be modified a bit. If CONFIG_PREEMPTION=n and we are in _"can resched but no need to resched"_ situation, we miss a chance to run ghost_commit_greedy_txn().

**Comment by neelnatu** [comment]
That's correct, we should call ghost_commit_greedy_txn() first because it may affect the 'need to resched' condition.

**Pull request closed without merging**
